import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ReactQueryProvider } from "@/lib/providers/ReactQueryProvider";
import { StoreProvider } from "@/lib/providers/StoreProvider";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	return (
		<ReactQueryProvider>
			<StoreProvider>
				<html lang="en">
					<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
						{children}
						<ToastContainer />
					</body>
				</html>
			</StoreProvider>
		</ReactQueryProvider>
	);
}
